spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # create | create-drop | update | validate | none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://192.168.0.2:5433/postgresdb
    username: postgres
    password: admin123
jwt:
  issuer: dangtong@gmail.com
  secret_key: study-springboot

#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop # create | create-drop | update | validate | none
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        format_sql: true
#    defer-datasource-initialization: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
##  h2:
##    console:
##      enabled: false
#  jwt:
#    issuer: dangtong@gmail.com
#    secret_key: study-springboot