apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.domain_name }}-db-secret
type: Opaque
data:
  MYSQL_PASSWORD: {{ .Values.db.mysql_password | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.db.mysql_root_password | b64enc }}