apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.domain_name }}-mysql-svc
spec:
  selector:
    app: {{ .Values.domain_name }}-mysql
  ports:
    - name: mysql-svc
      protocol: TCP
      port: 3306