apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.domain_name }}-deploy
  labels:
    app:  {{ .Values.domain_name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.domain_name }}
  replicas: 3
  template:
    metadata:
      labels:
        app:  {{ .Values.domain_name }}
    spec:
      initContainers:
        - name: check-mysql-ready
          image: mysql:8.0
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.domain_name }}-db-secret
                  key: MYSQL_PASSWORD
          command: ['sh',
                    '-c',
                    'until mysqladmin ping -u {{ .Values.db.mysql_user }} -p${MYSQL_PASSWORD} -h {{ .Values.domain_name }}-mysql-svc.{{ .Release.Namespace }}; do echo waiting for database; sleep 2; done;']
      containers:
        - name:  {{ .Values.domain_name }}
          image: {{ .Values.deploy.app_image | default "dangtong/istory" }}
          envFrom:
            - configMapRef:
                name: {{ .Values.domain_name }}-app-config
          env:
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.domain_name }}-db-secret
                  key: MYSQL_PASSWORD
            - name: spring.datasource.username
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.domain_name }}-db-config
                  key: MYSQL_USER
          resources:
            requests:
              cpu: 300m
              memory: 500Mi
            limits:
              cpu: 400m
              memory: 600Mi
          readinessProbe:
            httpGet:
              path: /actuator
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 3
            successThreshold: 2
            failureThreshold: 3
            periodSeconds: 10
          ports:
            - containerPort:  3306
              name:  {{ .Values.domain_name }}
      volumes:
        - name: application-config
          configMap:
            name: {{ .Values.domain_name }}-app-config
      restartPolicy: Always