apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: {{ .Values.domain_name }}-mysql
spec:
  containers:
    - image: {{ .Values.db.db_image | default "mysql/mysql-server" }}
      name: mysql
      resources:
        requests:
          cpu: "500m"
          memory: "500Mi"
        limits:
          cpu: "600m"
          memory: "600Mi"
      envFrom:
        - secretRef:
            name: {{ .Values.domain_name }}-db-secret
        - configMapRef:
            name: {{ .Values.domain_name }}-db-config
      ports:
        - containerPort: 3306
          name: mysql
      {{ if eq .Values.db.use_persistent "yes" }}
      volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      {{ end }}
  {{ if eq .Values.db.use_persistent "yes" }}
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: {{ .Values.domain_name }}-mysql-pv-claim
  {{ end }}