apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-persistent
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: {{ .Values.db.disk_recliam_policy | default "Retain"}}
parameters:
  type: {{ .Values.db.disk_grade | default "gp2" }}
  fsType: ext4
volumeBindingMode: WaitForFirstConsumer